### ISSUE TITLE
Package API

### ISSUE THREAD

**Issue by JMitnik** [JMitnik/FacialDebiasing#47]
## Todo's for what we need for the minimal (flexible) API

- [ ] Docstrings
- [x] Controlling main-structure from one config
- [ ] Clearly defined main functions (trainer / evaluator / plotter?): higher-level and lower-level functions so that one can train their own methods
- [ ] Adjustable layers
- [ ] Variable readable datasets (different sources for example)
- [ ] Alpha dependent on number images
